// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"calisthenics-content-api/api"
	"calisthenics-content-api/cache"
	"calisthenics-content-api/config"
	"calisthenics-content-api/data/repository"
	"calisthenics-content-api/middleware"
	"calisthenics-content-api/service"
	"fmt"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"github.com/spf13/viper"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp() *echo.Echo {
	db := NewDatabase()
	iMediaRepository := repository.NewMediaRepository(db)
	iMediaService := service.NewMediaService(iMediaRepository)
	iCacheService := cache.NewCacheManager()
	iMediaCacheService := cache.NewMediaCacheService(iCacheService)
	iContentRepository := repository.NewContentRepository(db)
	iContentService := service.NewContentService(iContentRepository)
	iMediaCacheOperations := service.NewMediaCacheOperations(iMediaService, iMediaCacheService, iContentService)
	iContentCacheService := cache.NewContentCacheService(iCacheService)
	iContentCacheOperations := service.NewContentCacheOperations(iContentService, iContentCacheService)
	iGenreRepository := repository.NewGenreRepository(db)
	iGenreService := service.NewGenreService(iGenreRepository)
	iGenreCacheService := cache.NewGenreCacheService(iCacheService)
	iGenreCacheOperations := service.NewGenreCacheOperations(iGenreService, iGenreCacheService)
	cacheController := api.NewCacheController(iMediaCacheOperations, iContentCacheOperations, iGenreCacheOperations)
	iGenreOperations := service.NewGenreOperations(iGenreService, iGenreCacheService)
	genreController := api.NewGenreController(iGenreOperations)
	iContentOperations := service.NewContentOperations(iContentService, iContentCacheService)
	contentController := api.NewContentController(iContentOperations)
	iInitCacheService := service.NewInitCacheService(iContentCacheOperations, iGenreCacheOperations, iMediaCacheOperations)
	echoEcho := InitRoutes(cacheController, genreController, contentController, iInitCacheService)
	return echoEcho
}

// wire.go:

var GeneralSet = wire.NewSet(NewDatabase, InitRoutes, cache.NewCacheManager)

var RepositorySet = wire.NewSet(repository.NewContentRepository, repository.NewMediaRepository, repository.NewGenreRepository)

var DomainServiceSet = wire.NewSet(service.NewContentService, service.NewMediaService, service.NewGenreService, service.NewInitCacheService)

var CacheServiceSet = wire.NewSet(cache.NewMediaCacheService, cache.NewContentCacheService, cache.NewGenreCacheService)

var ServiceSet = wire.NewSet(service.NewMediaOperations, service.NewContentOperations, service.NewGenreOperations, service.NewMediaCacheOperations, service.NewContentCacheOperations, service.NewGenreCacheOperations)

var ControllerSet = wire.NewSet(api.NewCacheController, api.NewGenreController, api.NewContentController)

func NewDatabase() *gorm.DB {
	dbUser := viper.GetString("database.user")
	dbPassword := viper.GetString("database.password")
	dbName := viper.GetString("database.name")
	db, err := gorm.Open(postgres.Open(fmt.Sprintf("user=%s dbname=%s password=%s sslmode=disable", dbUser, dbName, dbPassword)))
	if err != nil {
		panic("Failed to connect to the database")
	}
	err = db.AutoMigrate()
	if err != nil {
		panic("Failed to migrate database")
	}
	return db
}

func InitRoutes(
	cacheController *api.CacheController,
	genreController *api.GenreController,
	contentController *api.ContentController,
	initCacheService service.IInitCacheService,
) *echo.Echo {
	e := echo.New()
	e.Use(middleware.ServiceContextMiddleware)
	cacheController.InitCacheRoutes(e)
	genreController.InitGenreRoutes(e)
	e.Validator = &config.CustomValidator{Validator: validator.New()}

	return e
}
