// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

// Injectors from wire.go:

func InitializeApp() *echo.Echo {
	echoEcho := InitRoutes()
	return echoEcho
}

// wire.go:

var GeneralSet = wire.NewSet(InitRoutes)

var IntegrationSet = wire.NewSet()

var RepositorySet = wire.NewSet()

var DomainServiceSet = wire.NewSet()

var CacheServiceSet = wire.NewSet()

var ServiceSet = wire.NewSet()

var ControllerSet = wire.NewSet()

func InitRoutes() *echo.Echo {
	e := echo.New()
	e.Use(middleware.Static("/medias/"))
	e.GET("/medias/:file", func(c echo.Context) error {
		fileName := c.Param("file")
		return c.Attachment("medias/"+fileName, fileName)
	})
	return e
}
